### ISSUE TITLE
Add new POPS action to white list of actions

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-api#77]
ADO issue: https://dcp-paperless.visualstudio.com/dcp-paperless-dynamics/_queries/edit/10100/?triage=true

We need to include a new action code, "SG" to our whitelist of actions we display in the app. This requires updating multiple SQL queries in the API.

**Comment by trbmcginnis** [comment]
Code: `SG`
Full name: `POPS Signage`
ULURP: `Non-ULURP`
Description: ???

**Comment by bean75** [comment]
Is this too much? 
In 2017, the New York City Council adopted Local Law 116 as amended by Local Law 250 (“Local Law”), requiring public space signage at all new and existing privately owned public spaces (“POPS”). In 2019, the Department of City Planning (“DCP”) updated the POPS logo, which now must be included on such signage. POPS Signage actions indicate that an existing Privately Owned Public Space is updating its signage to comply with these regulations.

**Comment by trbmcginnis** [comment]
No that's great, thanks!

**Comment by trbmcginnis** [comment]
This change will now be highlighted in #530
